service: default
runtime: nodejs10
env: standard

manual_scaling:
  instances: 1

# edit
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /images
  static_dir: public/assets/images
- url: /stylesheets
  static_dir: public/assets/stylesheets
- url: /scripts
  static_dir: public/assets/scripts
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

  #error_handlers:
  #- file: default_error.html

# add error handler files
  #- error_code: over_quota
  #  file: over-quota.html
  #- error_code: timeout
  #  file: timeout.html

# verify purpose
#inbound_services:
  #- warmup