service: client
runtime: nodejs10
env: standard

handlers:
- url: /images
  static_dir: public/assets/images
- url: /stylesheets
  static_dir: public/assets/stylesheets
- url: /scripts
  static_dir: public/assets/scripts
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto