/* AUTH */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

/* DATA */

// years
export const LOADING_YEARS = "LOADING_YEARS";
export const FETCH_YEARS = "FETCH_YEARS";
export const EDIT_YEAR = "EDIT_YEAR";
export const CREATE_YEAR = "CREATE_YEAR";
export const UPDATE_YEAR = "UPDATE_YEAR";
export const DELETE_YEAR = "DELETE_YEAR";

// terms
export const LOADING_TERMS = "LOADING_TERMS";
export const FETCH_TERMS = "FETCH_TERMS";
export const EDIT_TERM = "EDIT_TERM";
export const CREATE_TERM = "CREATE_TERM";
export const UPDATE_TERM = "UPDATE_TERM";
export const DELETE_TERM = "DELETE_TERM";

// courses
export const LOADING_COURSES = "LOADING_COURSES";
export const FETCH_COURSES = "FETCH_COURSES";
export const EDIT_COURSE = "EDIT_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

// modules
export const LOADING_MODULES = "LOADING_MODULES";
export const FETCH_MODULES = "FETCH_MODULES";
export const EDIT_MODULE = "EDIT_MODULE";
export const CREATE_MODULE = "CREATE_MODULE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const DELETE_MODULE = "DELETE_MODULE";

// classes
export const LOADING_CLASSES = "LOADING_CLASSES";
export const FETCH_CLASSES = "FETCH_CLASSES";
export const EDIT_CLASS = "EDIT_CLASS";
export const CREATE_CLASS = "CREATE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";

// evaluations
export const LOADING_EVALUATIONS = "LOADING_EVALUATIONS";
export const FETCH_EVALUATIONS = "FETCH_EVALUATIONS";
export const EDIT_EVALUATION = "EDIT_EVALUATION";
export const CREATE_EVALUATION = "CREATE_EVALUATION";
export const UPDATE_EVALUATION = "UPDATE_EVALUATION";
export const DELETE_EVALUATION = "DELETE_EVALUATION";

// tasks
export const LOADING_TASKS = "LOADING_TERMS";
export const FETCH_TASKS = "FETCH_TASKS";
export const EDIT_TASK = "EDIT_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

// settings
export const LOADING_SETTINGS = "LOADING_SETTINGS";

export const FETCH_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const FETCH_PASSWORD = "GET_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const FETCH_PREFERENCES = "GET_PREFERENCES";
export const UPDATE_PREFERENCES = "UPDATE_PREFERENCES";

export const FETCH_INTEGRATIONS = "GET_INTEGRATIONS";
export const EDIT_INTEGRATION = "EDIT_INTEGRATION";
export const CREATE_INTEGRATION = "CREATE_INTEGRATION";
export const UPDATE_INTEGRATION = "UPDATE_INTEGRATION";
export const DELETE_INTEGRATION = "DELETE_INTEGRATION";

/* ORGANISMS */

// nav
export const ACTIVATE_DASHBOARD = "ACTIVATE_DASHBOARD";
export const ACTIVATE_CALENDAR = "ACTIVATE_CALENDAR";
export const ACTIVATE_TASKS = "ACTIVATE_TASKS"; 
export const ACTIVATE_EVALUATIONS = "ACTIVATE_EVALUATIONS";
export const ACTIVATE_COURSES = "ACTIVATE_COURSES";
export const ACTIVATE_SEARCH = "ACTIVATE_SEARCH";
export const ACTIVATE_SETTINGS = "ACTIVATE_SETTINGS";
export const ACTIVATE_HELP = "ACTIVATE_HELP";

/* MOLECULES */
export const COUNT_DATA = "COUNT_DATA";
